version: '3.8'

services:
  app:
    build: .
    image: restapi
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restapiDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/restapiDB
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: restapiDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"